const fs = require('fs');
const path = require('path');

module.exports = {
    name: 'generate-lua',
    description: 'Generate a Lua file with the given content.',
    options: [
        {
            name: 'content',
            type: 3, // STRING
            description: 'The content to write to the Lua file.',
            required: true,
        },
    ],
    async execute(interaction) {
        const content = interaction.options.getString('content');

        // Buat isi file Lua
        const luaContent = `-- Generated by Discord Bot\n-- Content:\n${content}`;

        // Nama file
        const fileName = `generated_${Date.now()}.lua`;
        const filePath = path.join(__dirname, fileName);

        // Simpan file di lokal
        fs.writeFileSync(filePath, luaContent);

        // Kirim file ke user
        await interaction.reply({
            content: 'Here is your Lua file!',
            files: [filePath],
        });

        // Hapus file setelah dikirim (opsional)
        fs.unlinkSync(filePath);
    },
};
